variables:
    PLUGIN_NAME: 'dataverse'

include:
  - project: 'thiago/modelos-para-integracao-continua-test'
    ref: main
    file:
      - 'templates/groups/pkp_plugin.yml'
      - 'templates/groups/ops_plugins_unit_tests_model.yml'
      - 'templates/groups/ops_plugins_cypress_tests_model.yml'

integration_tests:
  before_script:
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt --fix-broken install ./google-chrome-stable_current_amd64.deb

