variables:
    PLUGIN_NAME: 'dataverse'
    SAST_EXCLUDED_PATHS: classes/creators/DataversePackageCreator.inc.php, tests/DataversePackageCreatorTest.php, libs/swordappv2-php-library
    
include:
  - project: 'documentacao-e-tarefas/modelosparaintegracaocontinua'
    ref: main
    file:
      - 'templates/groups/pkp_plugin_mirrored.yml'
