variables:
    PLUGIN_NAME: 'dataverse'
    
include:
  - project: 'documentacao-e-tarefas/modelosparaintegracaocontinua'
    ref: main
    file:
      - 'templates/groups/pkp_plugin_mirrored.yml'

      
